- name: Install required MySQL packages
  ansible.builtin.yum:
    name:
      - python3-pymysql
      - mysql-server
    state: present
    update_cache: yes

- name: Install MariaDB
  ansible.builtin.yum:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Start and enable MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Set root password for MariaDB
  ansible.builtin.mysql_user:
    name: root
    password: "{{ db_root_password }}"
    host: '127.0.0.1'
    state: present

- name: Create a database for the application
  ansible.builtin.mysql_db:
    name: app_db
    state: present

- name: Create a user for the application
  ansible.builtin.mysql_user:
    name: app_user
    password: "{{ db_app_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
- name: Allow remote connections by updating bind address
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present